adb pull system/bin/btnvtool system/bin/btnvtool 
adb pull system/bin/ds_fmc_appd system/bin/ds_fmc_appd 
adb pull system/bin/e2fsck system/bin/e2fsck 
adb pull system/bin/fmconfig system/bin/fmconfig 
adb pull system/bin/hci_qcomm_init system/bin/hci_qcomm_init 
adb pull system/bin/keystore system/bin/keystore 
adb pull system/bin/mpdecision system/bin/mpdecision 
adb pull system/bin/netmgrd system/bin/netmgrd 
adb pull system/bin/qmuxd system/bin/qmuxd 
adb pull system/bin/rmt_storage system/bin/rmt_storage 
adb pull system/bin/thermald system/bin/thermald 
adb pull system/bin/usbhub system/bin/usbhub 
adb pull system/bin/usbhub_init system/bin/usbhub_init 
adb pull system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin 
adb pull system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin 
adb pull system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin 
adb pull system/etc/firmware/yamato_pfp.fw system/etc/firmware/yamato_pfp.fw 
adb pull system/etc/firmware/yamato_pm4.fw system/etc/firmware/yamato_pm4.fw 
adb pull system/etc/wifi/wpa_supplicant.conf system/etc/wifi/wpa_supplicant.conf 
adb pull system/etc/audio_effects.conf system/etc/audio_effects.conf 
adb pull system/etc/audio_policy.conf system/etc/audio_policy.conf 
adb pull system/etc/gps.conf system/etc/gps.conf 
adb pull system/etc/thermald-8x25-msm1-pmic_therm.conf system/etc/thermald-8x25-msm1-pmic_therm.conf 
adb pull system/etc/thermald-8x25-msm2-msm_therm.conf system/etc/thermald-8x25-msm2-msm_therm.conf 
adb pull system/etc/thermald-8x25-msm2-pmic_therm.conf system/etc/thermald-8x25-msm2-pmic_therm.conf 
adb pull system/etc/thermald-8x25-msm2-msm_therm.conf system/etc/thermald-8x25-msm2-msm_therm.conf 
adb pull system/lib/egl/eglsubAndroid.so system/lib/egl/eglsubAndroid.so 
adb pull system/lib/egl/libEGL_adreno200.so system/lib/egl/libEGL_adreno200.so 
adb pull system/lib/egl/libGLES_android.so system/lib/egl/libGLES_android.so 
adb pull system/lib/egl/libGLESv1_CM_adreno200.so system/lib/egl/libGLESv1_CM_adreno200.so 
adb pull system/lib/egl/libGLESv2_adreno200.so system/lib/egl/libGLESv2_adreno200.so 
adb pull system/lib/egl/libq3dtools_adreno200.so system/lib/egl/libq3dtools_adreno200.so 
adb pull system/lib/hw/audio.primary.default.so system/lib/hw/audio.primary.default.so 
adb pull system/lib/hw/audio.primary.msm7627a.so system/lib/hw/audio.primary.msm7627a.so 
adb pull system/lib/hw/audio_policy.default.so system/lib/hw/audio_policy.default.so 
adb pull system/lib/hw/audio_policy.msm7627a.so system/lib/hw/audio_policy.msm7627a.so 
adb pull system/lib/hw/camera.msm7627a.so system/lib/hw/camera.msm7627a.so 
adb pull system/lib/hw/copybit.msm7627a.so system/lib/hw/copybit.msm7627a.so 
adb pull system/lib/hw/gps.default.so system/lib/hw/gps.default.so 
adb pull system/lib/hw/gralloc.msm7627a.so system/lib/hw/gralloc.msm7627a.so 
adb pull system/lib/hw/hwcomposer.msm7627a.so system/lib/hw/hwcomposer.msm7627a.so 
adb pull system/lib/hw/lights.msm7627a.so system/lib/hw/lights.msm7627a.so 
adb pull system/lib/hw/power.default.so system/lib/hw/power.default.so 
adb pull system/lib/hw/sensors.default.so system/lib/hw/sensors.default.so 
adb pull system/lib/libgemini.so system/lib/libgemini.so 
adb pull system/lib/libgps.so system/lib/libgps.so 
adb pull system/lib/libgps.utils.so system/lib/libgps.utils.so 
adb pull system/lib/libidl.so system/lib/libidl.so 
adb pull system/lib/libimage-jpeg-enc-omx-comp.so system/lib/libimage-jpeg-enc-omx-comp.so 
adb pull system/lib/libimage-omx-common.so system/lib/libimage-omx-common.so 
adb pull system/lib/libloc_adapter.so system/lib/libloc_adapter.so 
adb pull system/lib/libloc_eng.so system/lib/libloc_eng.so 
adb pull system/lib/libmmcamera_faceproc.so system/lib/libmmcamera_faceproc.so 
adb pull system/lib/libmmcamera_frameproc.so system/lib/libmmcamera_frameproc.so 
adb pull system/lib/libmmcamera_hdr_lib.so system/lib/libmmcamera_hdr_lib.so 
adb pull system/lib/libmmcamera_image_stab.so system/lib/libmmcamera_image_stab.so 
adb pull system/lib/libmmcamera_interface2.so system/lib/libmmcamera_interface2.so 
adb pull system/lib/libmmcamera_statsproc31.so system/lib/libmmcamera_statsproc31.so 
adb pull system/lib/libmmcamera_wavelet_lib.so system/lib/libmmcamera_wavelet_lib.so 
adb pull system/lib/libmmjpeg.so system/lib/libmmjpeg.so 
adb pull system/lib/libmmstillomx.so system/lib/libmmstillomx.so 
adb pull system/lib/libnetmgr.so system/lib/libnetmgr.so 
adb pull system/lib/libqdi.so system/lib/libqdi.so 
adb pull system/lib/libqdp.so system/lib/libqdp.so 
adb pull system/lib/libqmi.so system/lib/libqmi.so 
adb pull system/lib/libqmi_client_qmux.so system/lib/libqmi_client_qmux.so 
adb pull system/lib/libril-qc-qmi-1.so system/lib/libril-qc-qmi-1.so
